### ISSUE TITLE
Não reconhece pasta media

### ISSUE THREAD

**Issue by fantonioluz** [pedro-coelho-dr/fdsproject#10]

**Comment by pedro-coelho-dr** [comment]
Desconfio que seja os settings.py: é preciso testar na maquina local e no AWS, (pode ter ligação com o link de referencia no models também)
![WhatsApp Image 2023-04-16 at 22 20 22](https://user-images.githubusercontent.com/111138996/232474386-367f4fc5-bc52-4216-ab72-41e62e86bed5.jpeg)
![WhatsApp Image 2023-04-16 at 22 18 39](https://user-images.githubusercontent.com/111138996/232474517-07b1f239-b67b-4353-af9f-113c8f057b5f.jpeg)

**Comment by fantonioluz** [comment]
Pasta media esta sendo reconhecida, era apenas ter uma pasta para media locale uma para o aws
