### ISSUE TITLE
Accordeon do Profile não funciona independente

### ISSUE THREAD

**Issue by fantonioluz** [pedro-coelho-dr/fdsproject#11]

**Comment by pedro-coelho-dr** [comment]
Clicar na seta para abri o acordeon, abre todos os itens do acordeon: possivelmente tags do bootstrap está errada

**Comment by fantonioluz** [comment]
Foi arrumado, era uma div que esta a mais no profile.html, @tharaujo17 refez os html para organizar os codigos e foi visto esse problema
