### ISSUE TITLE
Template da página do Admin

### ISSUE THREAD

**Issue by pedro-coelho-dr** [pedro-coelho-dr/fdsproject#4]
Página do admin está com um quadrado branco fora do lugar: escrito 'Toggle Theme'

**Comment by fantonioluz** [comment]
Mandar print do local, não encontrei o que foi referenciado no bug

**Comment by pedro-coelho-dr** [comment]
Não está bem resolvido, mas acredito que seja relacionado só ao venv mesmo.
Não está atrapalhando a funcionalidade em si, keep watchin
