### ISSUE TITLE
Bootstrap

### ISSUE THREAD

**Issue by pedro-coelho-dr** [pedro-coelho-dr/fdsproject#5]
No makemigrations está aparecendo algumas mensagens sobre bootstrap: mas não está impedindo de migrar.  Talvez seja algo dos requirements.txt novos, ou simplesmente integrarmos o bootstrap:
```
 File "C:\Users\pedro\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
```

**Comment by fantonioluz** [comment]
Acredito não ser do requirements novo, não tem nada de bootstrap nele, pode ser algum template do bootstrap que não exista mais

**Comment by pedro-coelho-dr** [comment]
Bootstrap tá funcional já.
